server:
    port: 9080
    context-path: /backend

logging:
    level:
        root: INFO
        tk: DEBUG

spring:
    datasource:
        name: sv
        url: jdbc:mysql://115.29.32.62:3306/sv
        username: root
        password: 7d428bc667
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: tk.mybatis.springboot.model com.liumapp.helloSv.backend.web.model
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:conf/mybatis-typehandler.xml

mapper:
    mappers:  com.liumapp.helloSv.backend.web.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

